---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-operator-rb
  labels:
    {{- include "kubesqlserver-operator.labels" (dict "global" .Values.global.labels "component" .Values.controller.labels) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-operator-role
subjects:
  - kind: ServiceAccount
    name: {{ include "kubesqlserver-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
